spring:
  application:
    name: platform
  # MySQL Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/pdf2data_db?createDatabaseIfNotExist=true
    username: root
    password: Stavan@1996
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/pdf2data_nosql

